---

# - hosts: osint
#   become: true
#   roles: 
#     - centos_osint_nginx

# - hosts: brute_ssh
#   become: true
#   roles:
#     - centos_weak_creds_ssh

# - hosts: shellshock
#   become: true
#   roles:
#     - centos_shellshock_apache

- hosts: smiley
  become: true
  roles:
    - centos_smiley_vsftpd

- hosts: wordpress
  become: true
  roles:
    #- ubuntu_wordpress
    - ubuntu_trigger_CVE-2017-1000382

