---
#- hosts: osint
#  become: true
#  roles: 
#    - centos_osint_nginx
#
#- hosts: brute_ssh
#  become: true
#  roles:
#    - centos_weak_creds_ssh
#       
#- hosts: smiley
#  become: true
#  roles:
#    - centos_smiley_vsftpd

       # - hosts: shellshock
       # become: true
       #roles:
       #- centos_shellshock_apache
       #  - hosts: mongo
       #    become: true
       #    roles: 
       #      - ubuntu_allow_all_mongodb
       # 

#- hosts: arbitrary_ftp
#  become: true
#  roles:
#    - ubuntu_arbitrary_ftp
#- hosts: allow_all_mongodb
#  become: true
#  roles:
#    - ubuntu_allow_all_mongodb

- hosts: weak_telnet
  become: true
  roles:
    - ubuntu_weak_creds_telnet
#
#- hosts: record
#  become: true
#  roles:
#    - record
