---

    - name: Install vsftpd
      package:
        name: vsftpd
        state: present

    - name: Copy over the vsftp config 
      copy:
        src: vsftpd.conf
        dest: /etc/vsftpd.conf

    - name: Reload and enable vsftp
      service:
        name: vsftpd
        state: started
        enabled: yes

    # - name: Add a scoring user
    #   user:
    #     name: scoring
    #     # Password = spaghettimonster
    #     password: $6$$rON4PwhoGsuYamMKJP7g8UOMaWExHuhZtSbAmb3XNnkSdLoRe0gBC/7Wodj6LnRb/ctYNXAMAGVddqjwTsOuz/
    #     groups: wheel
    #     uid: 9999

    - name: Create scoring directory
      file:
        path: /ftp_files
        state: directory
        mode: 0744

    - name: Copy ownership.txt to /
      copy:
        src: ownership.txt
        dest: /ftp_files/ownership.txt
        owner: root
        group: root