---

      - name: Install vsftpd
        package:
          name: vsftpd
          state: present

      - name: Copy over the vsftp config 
        copy:
         src: vsftpd.conf
         dest: /etc/vsftpd.conf

      - name: Reload and enable vsftp
        service:
         name: vsftpd
         state: started
         enabled: yes