---
  - remote_user: root
    tasks:

    - name: Adding hunter user for ssh brute force
      user:
        name: hunter
        shell: /bin/bash
        uid: 1024
        password: hunter2
        group: admin

